name: Build and Dockerize Maven Webapp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-tomcat-app .

      # Optional: Run container for test/debug (not exposed to the internet)
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name tomcat-app my-tomcat-app
          docker ps
